### ISSUE TITLE
do-magic.sh error copying referenceccdaservice.xml to tomcat localhost directory on vagrant up

### ISSUE THREAD

**Issue by drbgfc** [mieweb/vagrant-ccda-validator#2]
Steps to Reproduce:

Ran:
git clone --recurse-submodules https://github.com/mieweb/vagrant-ccda-validator.git
cd vagrant-ccda-validator
vagrant up
Waited

Tried opening up any of the following URLS:
http://localhost:8080/referenceccdaservice/static/validationui.html 
http://localhost:8080/referenceccdaservice/swagger-ui.html#/reference-ccda-validation-controller

Got 404

Looked at tomcat log, noticed that it didn't boot properly.
Looked at vagrant log, noticed the culprit:
    default: Copying config_extras...
    default: cp:
    default: cannot create regular file ‘/etc/tomcat/Catalina/localhost/referenceccdaservice.xml’
    default: : No such file or directory
    default: Done!

Note: This is related to line 15 in https://github.com/mieweb/vagrant-ccda-validator/blob/master/files/scripts/do-magic.sh
cp -f /etc/ccda/files/config_extra/referenceccdaservice.xml /etc/tomcat/Catalina/localhost/referenceccdaservice.xml

Manual Fix:
-SSHd into the VM
-stopped the tomcat instance using the service
-manually copied over referenceccdaservice.xml to /etc/tomcat/Catalina/localhost/
-restarted the tomcat instance using the service
-checked the logs (all good)
-now able to access and use the software at the respective URLs

If you would like the full logs let me know.
Thanks,
Dan

**Comment by wreiske** [comment]
Looking into this now. I think I fixed this recently? Let me look... Thanks for the report!

Edit: Probably just need to add `mkdir -p /etc/tomcat/Catalina/localhost/` right before the cp.

**Comment by wreiske** [comment]
@drbgfc please confirm the latest commit fixes your issue. If it still isn't working for you, please re-open this ticket.

Thanks!

**Comment by drbgfc** [comment]
Yes it works. I destroyed the VM, deleted the git cloned directory and reran the steps in the help file from scratch without issue.
The relevant output now shows no error:
    default: Copying config_extras...
    default: Done!

Thanks.

BTW I might as well mention. Scenario/content validation is not setup for this, but would not prove difficult to include. I can probably find time to submit a PR for that. Vocabulary is set up but of course is missing the licensed code systems and value sets (as it should be, for now). So one would have to manually add those to match SITE results. We are working towards a way to offer a package to make it simple. If that happens, combined with the scenario integration, this vagrant VM could be a complete solution of emulating the SITE C-CDA Validator in production.
